/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_avstudydemo2_player_DemoPlayer */

#ifndef _Included_com_example_avstudydemo2_player_DemoPlayer
#define _Included_com_example_avstudydemo2_player_DemoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_avstudydemo2_player_DemoPlayer
 * Method:    nativePrepare
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_avstudydemo2_player_DemoPlayer_nativePrepare
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_avstudydemo2_player_DemoPlayer
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_avstudydemo2_player_DemoPlayer_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_example_avstudydemo2_player_DemoPlayer
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_avstudydemo2_player_DemoPlayer_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_avstudydemo2_player_DemoPlayer
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_avstudydemo2_player_DemoPlayer_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_example_avstudydemo2_player_DemoPlayer
 * Method:    nativeSetSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_avstudydemo2_player_DemoPlayer_nativeSetSurface
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
